version: "3.9"

services:
  enrolldb:
    image: postgres:10.20-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - enrollment-private-network
    restart: unless-stopped

  enrollapp:
    image: jimmyej/management-enrollment:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - enrolldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://enrolldb:5432/${POSTGRES_DATABASE}
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - ENROLL_APP_SECRET=${APP_SECRET}
    networks:
      - enrollment-private-network

networks:
  enrollment-private-network:
    driver: bridge

volumes:
  postgres: